### ISSUE TITLE
web

### ISSUE THREAD

**Issue by aljopro** [jsdf/webpack-combine-loaders#7] opened 2016-11-04 14:36 UTC
webpack-combine-loaders version 2.0.2 causes npm to error out.
npm ERR! cb() never called!

steps to reproduce:
set webpack-combine-loaders version to 2.0.2 in package.json
run `npm update`

expected results
package should be install

actual results
`npm ERR! cb() never called!`

**Comment by jsdf** [comment] 2016-11-04 14:58
Dupe of #6

**Closed by jsdf** 2016-11-04 14:58 UTC
